from .display_title_n_logo import display_title_n_logo
from .display_short_desc import display_short_description
from .disp_long_descrip import display_long_description
from .disp_url import display_url
from .display_category import display_category
from .disp_proj_type import display_proj_type
from .display_screenshots import display_screenshots
from .display_videos import display_videos
from .display_usage import display_usage
from .disp_installation import display_installation
